### PR TITLE
Make the raw task layout const

### PR DESCRIPTION
**Pull request by james7132**
There are a few points that aren't 100% const in the std/core lib, but it's possible to compute the task layout at compile time to avoid the overhead of computing it for the task on every vtable call.

### CODE REVIEW

**Comment by james7132** [comment]
This seems to be failing CI due to an API that was unstable when const panics was stabilized. It compiles fine locally on my 1.61 environment. I don't know if bumping the MSRV past 1.57 is a good idea: it's already pretty recent. Any opinion on this? I can just revert `RawTask::from_ptr` being const if need be.

**Comment by taiki-e** [comment]
There are currently no plans to drop support for Rust 1.48 used by Debian stable.

**Comment by james7132** [comment]
If that's the case, would writing out a `const TASK_LAYOUT: Option<TaskLayout>` be OK then? It'd still have the unwrap at runtime, but it'd avoid computing the layout repeatedly at runtime.

**Comment by taiki-e** [comment]
Sounds good to me.

**Comment by james7132** [comment]
It does seem like a lot of these const methods are available, even in 1.48. I'll close this out for now.

**Pull request closed without merging**
