### PR TITLE
Add FallibleTask::is_finished()

### PR DESCRIPTION
**Pull request by mystenmark**
I'm unsure if there is a reason why this didn't exist already, but it seems straightforward to me.

### CODE REVIEW

**Review by notgull — APPROVED** [review]
This looks good to me!

@mystor Is there any reason why you didn't add this method while you were writing #21?

**Comment by taiki-e** [comment]
> Is there any reason why you didn't add this method while you were writing #21?

This is because FallibleTask is added in 4.1.0 (https://github.com/smol-rs/async-task/commit/3706c1e702ece1daa0b44e97e016f558800fb2ff) and Task::is_finished is added in 4.2.0 (https://github.com/smol-rs/async-task/commit/67d2a176feb0a22bd11df22f9c3a67e07b81e14a).

**Comment by taiki-e** [comment]
Thanks!

**Comment by mystor** [comment]
Yup, it just didn't exist at the time :-)

**Pull request merged**
